#!/bin/bash

# usage 
# for additional subjects (38,82,166,191,204) use forward_DN.nii file 
# for all other subjects use forward_qcraw.nii file


module load fsl/5.0.8
module load freesurfer

S=44
WORKDIRsave="/gpfs/M2Scratch/Monash076/simon/GenCog/subjects/1008.2.57.${S}/diffusion"

fslsplit ${WORKDIRsave}/forward_qcraw.nii -t
echo ${S}
	for V in 7 26;
	do 
	rm vol00${V}.nii.gz
	done

	fslmerge -t ${WORKDIRsave}/forward_qcraw.nii vol00*

	rm vol00* 
	cd ${WORKDIRsave}
	mri_convert ${WORKDIRsave}/forward_qcraw.nii.gz ${WORKDIRsave}/forward_qcraw.nii
	rm ${WORKDIRsave}/forward_qcraw.nii.gz


S=51
WORKDIRsave="/gpfs/M2Scratch/Monash076/simon/GenCog/subjects/1008.2.57.${S}/diffusion"
fslsplit ${WORKDIRsave}/forward_qcraw.nii -t
echo ${S}
	for V in 29 63;
	do 
	rm vol00${V}.nii.gz
	done

	fslmerge -t ${WORKDIRsave}/forward_qcraw.nii vol00*

	rm vol00* 
	cd ${WORKDIRsave}
	mri_convert ${WORKDIRsave}/forward_qcraw.nii.gz ${WORKDIRsave}/forward_qcraw.nii
	rm ${WORKDIRsave}/forward_qcraw.nii.gz



S=116
WORKDIRsave="/gpfs/M2Scratch/Monash076/simon/GenCog/subjects/1008.2.57.${S}/diffusion"
fslsplit ${WORKDIRsave}/forward_qcraw.nii -t
echo ${S}
	for V in 19 49 57;
	do 
	rm vol00${V}.nii.gz
	done

	fslmerge -t ${WORKDIRsave}/forward_qcraw.nii vol00*

	rm vol00* 
	cd ${WORKDIRsave}
	mri_convert ${WORKDIRsave}/forward_qcraw.nii.gz ${WORKDIRsave}/forward_qcraw.nii
	rm ${WORKDIRsave}/forward_qcraw.nii.gz


S=144
WORKDIRsave="/gpfs/M2Scratch/Monash076/simon/GenCog/subjects/1008.2.57.${S}/diffusion"
fslsplit ${WORKDIRsave}/forward_qcraw.nii -t
echo ${S}
	for V in 15 24 36;
	do 
	rm vol00${V}.nii.gz
	done

	fslmerge -t ${WORKDIRsave}/forward_qcraw.nii vol00*

	rm vol00* 
	cd ${WORKDIRsave}
	mri_convert ${WORKDIRsave}/forward_qcraw.nii.gz ${WORKDIRsave}/forward_qcraw.nii
	rm ${WORKDIRsave}/forward_qcraw.nii.gz


S=280
WORKDIRsave="/gpfs/M2Scratch/Monash076/simon/GenCog/subjects/1008.2.57.${S}/diffusion"
fslsplit ${WORKDIRsave}/forward_qcraw.nii -t
echo ${S}
	for V in 36 53;
	do 
	rm vol00${V}.nii.gz
	done

	fslmerge -t ${WORKDIRsave}/forward_qcraw.nii vol00*

	rm vol00* 
	cd ${WORKDIRsave}
	mri_convert ${WORKDIRsave}/forward_qcraw.nii.gz ${WORKDIRsave}/forward_qcraw.nii
	rm ${WORKDIRsave}/forward_qcraw.nii.gz


