#!/bin/bash

# usage 

# RemoveVolumes 116 ${Volumes} - first number - subject number, second imput - vector of volumes. 
function RemoveSingleVolume {
module load fsl/5.0.8
module load freesurfer

S=$1
Volume=$2

WORKDIRsave="/gpfs/M2Scratch/Monash076/simon/GenCog/subjects/1008.2.57.${S}/diffusion"
# for additional subjects (38,82,166,191,204) use forward_DN.nii file 
# for all other subjects use forward_qc.nii file
fslsplit ${WORKDIRsave}/forward.nii -t
echo ${S}
	for V in ${Volume};
	do 
	rm vol00${V}.nii.gz
	done

	fslmerge -t ${WORKDIRsave}/forward_qcraw.nii vol00*

	rm vol00* 
	cd ${WORKDIRsave}
	mri_convert ${WORKDIRsave}/forward_qcraw.nii.gz ${WORKDIRsave}/forward_qcraw.nii
	rm ${WORKDIRsave}/forward_qcraw.nii.gz
}


